name: Build Docker Redash 10

env:
  REDASH_VERSION: 10.1.0.b50633

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - .github/workflows/build-10.yml
      - Dockerfile

jobs:
  build-docker:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: frxyt/redash
          tags: |
            type=raw,value=${{ env.REDASH_VERSION }}-${{ github.sha }}-${{ steps.date.outputs.date }}
            type=raw,value=${{ env.REDASH_VERSION }}-${{ github.sha }}
            type=raw,value=${{ env.REDASH_VERSION }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            FRX_BUILD_COMMIT_DATE=${{ steps.date.outputs.date }}
            FRX_BUILD_COMMIT_SHA=${{ github.sha}}
            FRX_REDASH_VERSION=${{ env.REDASH_VERSION }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}